### ISSUE TITLE
Invariant Violation: Native module cannot be null.

### ISSUE THREAD

**Issue by w8r** [baochungit/expo-pixi-game-engine-demo#1]
I get this error trying to build your app

```
Mac OS 11.6.2 (20G314)
Node v16.13.2 (with npm 8.1.2)
```
![simulator_screenshot_E774B7B1-51A9-48DD-9EA0-7678C4CF01CD](https://user-images.githubusercontent.com/26884/152662941-dfcf7364-3884-4bb4-8e59-a9764cdc2a3b.png)

I am actually looking for ways of making `expo-pixi` work with Expo@44 and further, which is always giving me a lot of headache. So I wanted to learn from your experience

Any help would be appreciated, thanks a lot!

**Comment by baochungit** [comment]
It could be an issue with unsupported class on iOS. Actually there are a few things unnecessary that you can remove from the code. Try to put a comment on the whole line 7 of `/src/utils/index.js` and try again.

**Comment by w8r** [comment]
Thanks a lot! You were right, it only needs `sleep` function from that file. I was able to start it, but just like in my own previous experiments, it's impossibly slow in the emulator. Was it also the case for you?

**Comment by baochungit** [comment]
No, it's not my case since I prefer using my real device to check rather than emulators :D
Actually, from my experience, it's always slow in emulators (not only for expo pixi game).
Well, try to adjust hardware acceleration (especially the GPU driver) on the emulator to see if it helps.
